# Use the latest Node.js image as the base
FROM node:latest

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app/

# Set the default command to run when the container starts
CMD npm install && npm start